source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "12.0"

use_frameworks!

target 'MiaowShow' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.1'
pod 'MJExtension', '~> 3.0.10'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BarrageRenderer', '~> 1.8.0'
pod 'LFLiveKit', '2.6'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      if config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"].to_f < 12.0
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
      end
    end

    project.root_object.known_regions = ["en", "Base"]

    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"].to_f < 12.0
          config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
        end
      end
    end
  end
end
